version: "2"
authtoken: YOUR_NGROK_TOKEN_HERE
tunnels:
  math-platform:
    addr: 8000
    proto: http
    hostname: math-competition-platform.ngrok.io
    bind_tls: true
  math-platform-alt:
    addr: 8000
    proto: http
    bind_tls: true
region: us
console_ui: true
console_ui_color: transparent
log_level: info
log_format: logfmt
log: ngrok.log
