services:
  - type: web
    name: math-competition-platform
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn alhassan.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: alhassan.render_settings
      - key: DEBUG
        value: False
      - key: STUDENT_ACCESS_CODE
        value: ben25
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: .
      - key: DATABASE_URL
        fromDatabase:
          name: math-competition-db
          property: connectionString

  - type: pserv
    name: math-competition-db
    env: postgresql
    plan: free
    databaseName: math_competition
    user: math_user
