# Generated by Django 5.2.1 on 2025-05-12 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_type', models.CharField(choices=[('daily_stats', 'إحصائيات يومية'), ('weekly_stats', 'إحصائيات أسبوعية'), ('monthly_stats', 'إحصائيات شهرية'), ('grade_stats', 'إحصائيات حسب الصف'), ('operation_stats', 'إحصائيات حسب العمليات'), ('difficulty_stats', 'إحصائيات حسب الصعوبة')], max_length=20)),
                ('cache_key', models.CharField(help_text='Unique identifier for this cache entry', max_length=255)),
                ('data', models.JSONField(help_text='Cached JSON data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['cache_type', 'cache_key'], name='dashboard_s_cache_t_08ae21_idx'), models.Index(fields=['expires_at'], name='dashboard_s_expires_79d405_idx')],
                'unique_together': {('cache_type', 'cache_key')},
            },
        ),
    ]
