# Generated by Django 5.2.1 on 2025-05-28 00:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_participant_group_alter_competition_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'المستوى الأول'), (2, 'المستوى الثاني'), (3, 'المستوى الثالث'), (4, 'المستوى الرابع'), (5, 'جدول الضرب فقط'), (6, 'عمليات الجمع والطرح'), (7, 'عمليات القسمة فقط')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='mathquestion',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'المستوى الأول'), (2, 'المستوى الثاني'), (3, 'المستوى الثالث'), (4, 'المستوى الرابع'), (5, 'جدول الضرب فقط'), (6, 'عمليات الجمع والطرح'), (7, 'عمليات القسمة فقط')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
