# Generated by Django 5.2.1 on 2025-05-12 04:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MathQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('addition', 'جمع'), ('subtraction', 'طرح'), ('multiplication', 'ضرب'), ('division', 'قسمة')], max_length=15)),
                ('difficulty', models.IntegerField(choices=[(1, 'المستوى 1'), (2, 'المستوى 2'), (3, 'المستوى 3'), (4, 'المستوى 4')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('first_number', models.IntegerField()),
                ('second_number', models.IntegerField()),
                ('answer', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.IntegerField(choices=[(1, 'المستوى 1'), (2, 'المستوى 2'), (3, 'المستوى 3'), (4, 'المستوى 4')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0)),
                ('addition_correct', models.IntegerField(default=0)),
                ('subtraction_correct', models.IntegerField(default=0)),
                ('multiplication_correct', models.IntegerField(default=0)),
                ('division_correct', models.IntegerField(default=0)),
                ('addition_total', models.IntegerField(default=0)),
                ('subtraction_total', models.IntegerField(default=0)),
                ('multiplication_total', models.IntegerField(default=0)),
                ('division_total', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='competitions.competition')),
            ],
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.FloatField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('response_time', models.FloatField(blank=True, help_text='Time taken to answer in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='competitions.competition')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='competitions.mathquestion')),
            ],
        ),
    ]
