# Generated by Django 5.2.1

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('addition', 'الجمع'), ('subtraction', 'الطرح'), ('multiplication', 'الضرب'), ('division', 'القسمة'), ('mixed', 'مختلط')], max_length=20, verbose_name='نوع العملية')),
                ('difficulty', models.CharField(choices=[('easy', 'سهل'), ('medium', 'متوسط'), ('hard', 'صعب')], max_length=10, verbose_name='مستوى الصعوبة')),
                ('question_text', models.TextField(verbose_name='نص السؤال')),
                ('correct_answer', models.IntegerField(verbose_name='الإجابة الصحيحة')),
                ('grade_level', models.CharField(max_length=50, verbose_name='المستوى الدراسي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'سؤال',
                'verbose_name_plural': 'الأسئلة',
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, verbose_name='اسم الطالب')),
                ('grade_level', models.CharField(max_length=50, verbose_name='المستوى الدراسي')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='وقت البداية')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت الانتهاء')),
                ('total_questions', models.IntegerField(default=10, verbose_name='عدد الأسئلة')),
                ('correct_answers', models.IntegerField(default=0, verbose_name='الإجابات الصحيحة')),
                ('is_completed', models.BooleanField(default=False, verbose_name='مكتملة')),
                ('score', models.FloatField(default=0.0, verbose_name='النتيجة')),
            ],
            options={
                'verbose_name': 'مسابقة',
                'verbose_name_plural': 'المسابقات',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.IntegerField(verbose_name='إجابة الطالب')),
                ('is_correct', models.BooleanField(verbose_name='صحيحة')),
                ('answer_time', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإجابة')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition', verbose_name='المسابقة')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.question', verbose_name='السؤال')),
            ],
            options={
                'verbose_name': 'إجابة',
                'verbose_name_plural': 'الإجابات',
            },
        ),
    ]
