# Generated by Django 5.2.1 on 2025-05-28 00:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_alter_competition_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'المستوى الأول - المرحلة الأولى'), (2, 'المستوى الثاني - المرحلة الأولى'), (3, 'المستوى الثالث - المرحلة الأولى'), (4, 'المستوى الرابع - المرحلة الأولى'), (5, 'المستوى الخامس - المرحلة الأولى'), (6, 'المستوى السادس - المرحلة الأولى'), (7, 'المستوى الأول - المرحلة الثانية'), (8, 'المستوى الثاني - المرحلة الثانية'), (9, 'المستوى الثالث - المرحلة الثانية')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='mathquestion',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'المستوى الأول - المرحلة الأولى'), (2, 'المستوى الثاني - المرحلة الأولى'), (3, 'المستوى الثالث - المرحلة الأولى'), (4, 'المستوى الرابع - المرحلة الأولى'), (5, 'المستوى الخامس - المرحلة الأولى'), (6, 'المستوى السادس - المرحلة الأولى'), (7, 'المستوى الأول - المرحلة الثانية'), (8, 'المستوى الثاني - المرحلة الثانية'), (9, 'المستوى الثالث - المرحلة الثانية')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='mathquestion',
            name='operation',
            field=models.CharField(choices=[('addition', 'جمع'), ('subtraction', 'طرح'), ('multiplication', 'ضرب'), ('division', 'قسمة'), ('mixed_operations', 'عمليات مختلطة'), ('fractions', 'كسور وأعداد عشرية'), ('algebra', 'جبر'), ('geometry', 'هندسة'), ('trigonometry', 'مثلثات'), ('word_problems', 'مسائل تطبيقية')], max_length=20),
        ),
    ]
