# Generated by Django 5.2.1 on 2025-05-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_alter_competition_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathquestion',
            name='question_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mathquestion',
            name='first_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mathquestion',
            name='second_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
