# Generated by Django 5.2.1 on 2025-05-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_mathquestion_question_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionresult',
            name='algebra_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competitionresult',
            name='algebra_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competitionresult',
            name='fractions_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competitionresult',
            name='fractions_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competitionresult',
            name='geometry_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competitionresult',
            name='geometry_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competitionresult',
            name='mixed_operations_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competitionresult',
            name='mixed_operations_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competitionresult',
            name='trigonometry_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competitionresult',
            name='trigonometry_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competitionresult',
            name='word_problems_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competitionresult',
            name='word_problems_total',
            field=models.IntegerField(default=0),
        ),
    ]
