# Generated by Django 5.2.1 on 2025-05-29 22:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_competitionresult_algebra_correct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, verbose_name='اسم التلميذ')),
                ('grade', models.IntegerField(choices=[(1, 'المستوى الأول ابتدائي'), (2, 'المستوى الثاني ابتدائي'), (3, 'المستوى الثالث ابتدائي'), (4, 'المستوى الرابع ابتدائي'), (5, 'المستوى الخامس ابتدائي'), (6, 'المستوى السادس ابتدائي'), (7, 'المستوى الأول إعدادي'), (8, 'المستوى الثاني إعدادي'), (9, 'المستوى الثالث إعدادي')], verbose_name='المستوى الدراسي')),
                ('difficulty', models.IntegerField(choices=[(1, 'المستوى الأول - سهل'), (2, 'المستوى الثاني - متوسط'), (3, 'المستوى الثالث - متقدم'), (4, 'المستوى الرابع - صعب'), (5, 'المستوى الخامس - خبير'), (6, 'المستوى السادس - متقدم جداً')], verbose_name='مستوى الصعوبة')),
                ('session_code', models.CharField(default='ben25', max_length=20, verbose_name='رمز الدخول')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت البداية')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت الانتهاء')),
                ('is_completed', models.BooleanField(default=False, verbose_name='مكتملة')),
                ('total_questions', models.IntegerField(default=0, verbose_name='إجمالي الأسئلة')),
                ('correct_answers', models.IntegerField(default=0, verbose_name='الإجابات الصحيحة')),
                ('total_score', models.IntegerField(default=0, verbose_name='النقاط الإجمالية')),
                ('addition_correct', models.IntegerField(default=0, verbose_name='الجمع الصحيح')),
                ('addition_total', models.IntegerField(default=0, verbose_name='إجمالي الجمع')),
                ('subtraction_correct', models.IntegerField(default=0, verbose_name='الطرح الصحيح')),
                ('subtraction_total', models.IntegerField(default=0, verbose_name='إجمالي الطرح')),
                ('multiplication_correct', models.IntegerField(default=0, verbose_name='الضرب الصحيح')),
                ('multiplication_total', models.IntegerField(default=0, verbose_name='إجمالي الضرب')),
                ('division_correct', models.IntegerField(default=0, verbose_name='القسمة الصحيحة')),
                ('division_total', models.IntegerField(default=0, verbose_name='إجمالي القسمة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='معلومات المتصفح')),
            ],
            options={
                'verbose_name': 'جلسة تلميذ',
                'verbose_name_plural': 'جلسات التلاميذ',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='StudentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=20, verbose_name='نوع العملية')),
                ('first_number', models.IntegerField(verbose_name='الرقم الأول')),
                ('second_number', models.IntegerField(verbose_name='الرقم الثاني')),
                ('correct_answer', models.IntegerField(verbose_name='الإجابة الصحيحة')),
                ('student_answer', models.IntegerField(blank=True, null=True, verbose_name='إجابة التلميذ')),
                ('is_correct', models.BooleanField(default=False, verbose_name='صحيحة')),
                ('response_time', models.FloatField(blank=True, null=True, verbose_name='وقت الإجابة (ثانية)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت الإنشاء')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='competitions.studentsession', verbose_name='الجلسة')),
            ],
            options={
                'verbose_name': 'إجابة تلميذ',
                'verbose_name_plural': 'إجابات التلاميذ',
                'ordering': ['created_at'],
            },
        ),
    ]
