# Generated by Django 5.2.1 on 2025-06-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_alter_studentsession_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsession',
            name='session_code',
            field=models.CharField(max_length=20, verbose_name='رمز الدخول'),
        ),
    ]
