# Generated by Django 5.2.1 on 2025-05-12 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('grade', models.IntegerField(choices=[(1, 'الأول ابتدائي'), (2, 'الثاني ابتدائي'), (3, 'الثالث ابتدائي'), (4, 'الرابع ابتدائي'), (5, 'الخامس ابتدائي'), (6, 'السادس ابتدائي'), (7, 'الأول إعدادي'), (8, 'الثاني إعدادي'), (9, 'الثالث إعدادي')], verbose_name='الصف الدراسي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'مشارك',
                'verbose_name_plural': 'المشاركون',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='competition',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competition',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='competitions.participant'),
        ),
    ]
